name: Nightly ARIMA Training

on:
  schedule:
    - cron: '0 6 * * *'  # every day at 06:00 UTC
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run ARIMA training
        run: |
          python arima_batch_train.py

      - name: Upload models
        uses: actions/upload-artifact@v3
        with:
          name: arima-models
          path: arima_models/
